export const ROUTER_URL = {
  HOME: "/",
  ORDER: "/order",
  STORE_LOCATOR: "/he-thong-cua-hang",
  ABOUT: "/about",
  CONTACT: "/contact",
  LOGIN: "/login",
  REGISTER: "/register",
  RESET_PASSWORD: "/reset-password",
  PROFILE: "/profile",

  // Browse & Product
  CATEGORIES: "/categories",
  PRODUCTS: "/products",
  PRODUCT_DETAIL: "/products/:id",

  ADMIN: "/admin",
  ADMIN_LOGIN: "/admin/login",
  ADMIN_ROUTES: {
    DASHBOARD: "dashboard",
    USERS: "users",
    ORDERS: "orders",
    ORDER_DETAIL: "orders/:id",
    CUSTOMERS: "customers",
    CUSTOMER_DETAIL: "customers/:id",
    PAYMENTS: "payments",
    PAYMENT_DETAIL: "payments/:id",
    LOYALTY: "loyalty",
    PRODUCTS: "products",
    FRANCHISE_LIST: "franchises",
    FRANCHISE_DETAIL: "franchises/:id",
    FRANCHISE_CREATE: "franchises/create",
    INVENTORY_BY_FRANCHISE: "franchises/:id/inventory",
  },
} as const;
